"""Code corpus filtering and preparation for pretraining.

Filters and prepares code files for pretraining by rejecting binary,
minified, generated, or too-long files.
"""

import hashlib
import os
from typing import List, Tuple

# Maximum file size in characters
MAX_FILE_LENGTH = 100_000

# Maximum line length (files with very long lines are likely minified)
MAX_LINE_LENGTH = 500

# Minimum file length
MIN_FILE_LENGTH = 50

# Binary/generated markers
BINARY_EXTENSIONS = {
    ".pyc", ".pyo", ".so", ".dll", ".exe", ".bin", ".o", ".a",
    ".class", ".jar", ".war", ".ear",
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg",
    ".pdf", ".doc", ".docx", ".xls",
    ".zip", ".tar", ".gz", ".bz2", ".7z",
    ".woff", ".woff2", ".ttf", ".eot",
    ".mp3", ".mp4", ".avi", ".mov",
    ".db", ".sqlite", ".sqlite3",
}

GENERATED_MARKERS = [
    "# DO NOT EDIT",
    "# AUTO-GENERATED",
    "// AUTO-GENERATED",
    "/* AUTO-GENERATED",
    "# This file is auto-generated",
    "// This file is auto-generated",
    "# Generated by",
    "// Generated by",
    "@generated",
    "AUTOGENERATED FILE",
]

MINIFIED_INDICATORS = [
    # Files with very few newlines relative to length are likely minified
]


def filter_file(path: str, content: str) -> bool:
    """Determine whether a file should be included in the pretraining corpus.

    Args:
        path: File path (used for extension checks)
        content: File content as string

    Returns:
        True if the file should be INCLUDED, False if it should be rejected.
    """
    # Check extension
    _, ext = os.path.splitext(path)
    if ext.lower() in BINARY_EXTENSIONS:
        return False

    # Check content length
    if len(content) > MAX_FILE_LENGTH:
        return False
    if len(content) < MIN_FILE_LENGTH:
        return False

    # Check for binary content (null bytes)
    if "\x00" in content:
        return False

    # Check for generated file markers
    first_lines = content[:2000]
    for marker in GENERATED_MARKERS:
        if marker in first_lines:
            return False

    # Check for minified files (very long lines)
    lines = content.split("\n")
    if lines:
        max_line = max(len(line) for line in lines[:100])
        if max_line > MAX_LINE_LENGTH and len(lines) < 10:
            return False

    # Check ratio of printable characters
    printable_count = sum(1 for c in content if c.isprintable() or c in "\n\t\r")
    if len(content) > 0 and printable_count / len(content) < 0.85:
        return False

    return True


def extract_python_files(repo_path: str) -> List[Tuple[str, str]]:
    """Extract all Python files from a repository path.

    Args:
        repo_path: Path to the repository root

    Returns:
        List of (relative_path, content) tuples for valid Python files.
    """
    results = []

    for root, dirs, files in os.walk(repo_path):
        # Skip hidden directories and common non-source dirs
        dirs[:] = [
            d for d in dirs
            if not d.startswith(".")
            and d not in {"__pycache__", "node_modules", ".git", "venv", "env", ".venv"}
        ]

        for filename in files:
            if not filename.endswith(".py"):
                continue

            filepath = os.path.join(root, filename)
            rel_path = os.path.relpath(filepath, repo_path)

            try:
                with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                    content = f.read()
            except (OSError, IOError):
                continue

            if filter_file(rel_path, content):
                results.append((rel_path, content))

    return results


def deduplicate_by_hash(files: List[Tuple[str, str]]) -> List[Tuple[str, str]]:
    """Remove duplicate files based on content hash.

    Args:
        files: List of (path, content) tuples

    Returns:
        Deduplicated list (first occurrence kept).
    """
    seen_hashes = set()
    unique_files = []

    for path, content in files:
        content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
        if content_hash not in seen_hashes:
            seen_hashes.add(content_hash)
            unique_files.append((path, content))

    return unique_files
